version: '3'
services:
  db:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3307:3306"
    tty: true
  app:
    build:
      context: ./api-server
    volumes:
      - "./api-server:/src"
    container_name: api-server
    ports:
      - "8080:8080"
    tty: true
    # command: "go run /src/main.go"
    depends_on:
      - db